"""add timestamp column

Revision ID: 119ef369528d
Revises: 5a99fc895bba
Create Date: 2018-05-12 18:19:34.002702

"""

# revision identifiers, used by Alembic.
revision = '119ef369528d'
down_revision = '5a99fc895bba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f('ix_messages_time'), 'messages', ['time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_time'), table_name='messages')
    op.drop_column('messages', 'time')
    ### end Alembic commands ###
