"""rename time to timestamp

Revision ID: 20f3517c82aa
Revises: 2bc1f3e2e229
Create Date: 2018-05-12 19:30:00.211314

"""

# revision identifiers, used by Alembic.
revision = '20f3517c82aa'
down_revision = '2bc1f3e2e229'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'time', new_column_name='timestamp')
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.drop_index('ix_messages_time', table_name='messages')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'timestamp', new_column_name='time')
    op.create_index('ix_messages_time', 'messages', ['time'], unique=False)
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    ### end Alembic commands ###
