"""remove timestamp

Revision ID: 2bc1f3e2e229
Revises: 119ef369528d
Create Date: 2018-05-12 19:29:04.737569

"""

# revision identifiers, used by Alembic.
revision = '2bc1f3e2e229'
down_revision = '119ef369528d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_timestamp', table_name='messages')
    op.drop_column('messages', 'timestamp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_messages_timestamp', 'messages', ['timestamp'], unique=False)
    ### end Alembic commands ###
