"""add sender_user_id

Revision ID: 4262343ecf80
Revises: 48bf23fea4b
Create Date: 2017-10-16 22:40:21.900823

"""

# revision identifiers, used by Alembic.
revision = '4262343ecf80'
down_revision = '48bf23fea4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['sender_user_id'], ['id'])
    op.drop_column('messages', 'pruned')
    op.drop_column('messages', 'subject')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('pruned', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'sender_user_id')
    ### end Alembic commands ###
